# Generated by Django 3.2.16 on 2022-12-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.IntegerField()),
                ('P', models.IntegerField()),
                ('K', models.IntegerField()),
                ('Temperature', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Humidity', models.DecimalField(decimal_places=5, max_digits=5)),
                ('ph', models.DecimalField(decimal_places=5, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
